sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t yeonchulkim/nginx-app -f DockerFile.dev .

script:
  - docker run -e CI=true yeonchulkim/nginx-app npm run test -- --coverage

after_success:
  - echo "Test Success"
